**L1 Norm**

In [ ]:
from numpy import array
from numpy.linalg import norm
X = array([1, 2, 3, 4, 5])
print(X)
l1 = norm(X, 1)
print(l1)

[1 2 3 4 5]
15.0


**L2 Norm**

In [ ]:
l2 = norm(X)
print(l2)

7.416198487095663


**MAX Norm (L infinite)**

In [ ]:
from numpy import inf
maxnorm = norm(X, inf)
print(maxnorm)

5.0


**Frobenius Norm (Matrix norm)**

In [ ]:
import numpy as np
X = np. array([[1, 2], [3, 4], [5, 6]]) 
print(X)
print()
norm(X)

[[1 2]
 [3 4]
 [5 6]]



9.539392014169456

**Other Matrix Norms**

In [ ]:
import numpy as np
from numpy import inf
X = np. array([[1, 2], [3, 4], [5, 6]]) 
print(X)
a=np.linalg.norm(X,1)
print()
print(a)

[[1 2]
 [3 4]
 [5 6]]

12.0


In [ ]:
b=np.linalg.norm(X,2)
print(b)

9.525518091565107


In [ ]:
c=np.linalg.norm(X,inf)
print(c)

11.0
