In [ ]:
print('Naren Kumar Reddy')


Naren Kumar Reddy


In [ ]:
import numpy as np

In [ ]:
a=np.arctan(5)
a

1.373400766945016

In [ ]:
a=np.hypot(3,4)
a

5.0

In [ ]:
a=np.degrees(np.radians(np.degrees(np.arctan2(1,1))))
a

45.0

In [ ]:
a=np.arcsinh(1)
a

0.881373587019543

In [ ]:
a=np.arccosh(3.14)
a

1.810991348900196

In [ ]:
a=np.tanh(3.14)
a

0.9962602049458319

In [ ]:
a=np.fix(1.9)
a

1.0

In [ ]:
a=np.floor(-1.1)
a

-2.0

In [ ]:
a=np.ceil(1.1)
a

2.0

In [ ]:
a=np.trunc(1.5)
a

1.0

In [ ]:
a=np.cumprod([1,2,3,4])
print(a)

[ 1  2  6 24]


In [ ]:
a=np.cumsum([4,5,6])
print(a)
a=a+1
a

[ 4  9 15]


array([ 5, 10, 16])

In [ ]:
a=[2,6,7]
a=np.array(a)
a=a+1
a

array([3, 7, 8])

In [ ]:
a=np.cross([1,2,3],[4,5,6])
a

array([-3,  6, -3])

In [ ]:
a=np.log(2.71)
a

0.9969486348916096

In [ ]:
a=np.log10(100)
a

2.0

In [ ]:
a=np.log1p(1+2)
a

1.3862943611198906

In [ ]:
a=np.sign([-2,2])
a

array([-1,  1])

In [ ]:
a=np.fabs([-1,1,3,-3])
a

array([1., 1., 3., 3.])

In [ ]:
a=np.maximum([1,2,3],[4,0,6])
a

array([4, 2, 6])

In [ ]:
a=np.conjugate(1+2j)
a

(1-2j)

In [ ]:
a=np.conj(1-2j)
a

(1+2j)

In [ ]:
a=np.divmod(np.arange(8), 5)
a

(array([0, 0, 0, 0, 0, 1, 1, 1]), array([0, 1, 2, 3, 4, 0, 1, 2]))

In [ ]:
a=np.mod(5,2)
a

1

In [ ]:
a=np.power(2,5)
a

32

In [ ]:
a=np.gcd(2,6)
a

2

In [ ]:
a=np.sinc(range(1,10))
a

array([ 3.89817183e-17, -3.89817183e-17,  3.89817183e-17, -3.89817183e-17,
        3.89817183e-17, -3.89817183e-17,  3.89817183e-17, -3.89817183e-17,
        3.89817183e-17])

In [ ]:
x=np.arange(4).reshape(2,2)
y=np.arange(4,8).reshape(2,2)
z=np.vstack((x,y))
z

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
x=np.arange(4).reshape(2,2)
y=np.arange(4,8).reshape(2,2)
z=np.dstack((x,y))
z

array([[[0, 4],
        [1, 5]],

       [[2, 6],
        [3, 7]]])

In [ ]:
x=np.arange(4).reshape(2,2)
y=np.arange(4,8).reshape(2,2)
z=np.hstack((x,y))
z

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])